/**
 * Aggregate the batch stress reports into per-rule evidence.
 *
 * The batch index says how many plugins graded where; it does not say *why*, and
 * "why" is the only thing that decides whether the catalog is calibrated. A rule
 * firing 70 times across 91 real packages is either the ecosystem's most common
 * hazard or the catalog's most common bug, and the rendered reports already carry
 * the evidence needed to tell those apart — the file, the line, and the matched
 * text. This reads them back out and groups by rule.
 *
 * Reports are generated by `stress-top-plugins.mjs`; this is read-only over them.
 *
 * Usage:
 *   node scripts/stress-analyze.mjs                 # critical rules, with evidence
 *   node scripts/stress-analyze.mjs --severity HIGH
 *   node scripts/stress-analyze.mjs --dir /tmp/stress
 */

import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Parsed command line. */
function parseArgs(argv) {
  const out = { dir: join(REPO_ROOT, 'docs', 'stress'), severity: 'CRITICAL', evidence: 6 };
  for (let index = 0; index < argv.length; index += 1) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (flag === '--dir') out.dir = resolve(value ?? out.dir);
    else if (flag === '--severity') out.severity = String(value ?? '').toUpperCase();
    else if (flag === '--evidence') out.evidence = Number.parseInt(value ?? '', 10);
    else if (flag === '--help' || flag === '-h') {
      console.log('usage: stress-analyze.mjs [--dir DIR] [--severity CRITICAL|HIGH|MEDIUM|LOW] [--evidence N]');
      process.exit(0);
    } else continue;
    index += 1;
  }
  return out;
}

const HEADING = /^### .*?\/ (CRITICAL|HIGH|MEDIUM|LOW|INFO) \(/;
const FINDING = /^- \*\*.*?\*\* `([a-z][a-z0-9-]*\.[a-z0-9-]+)`/;
const EVIDENCE = /^\s+- `([^`]+)` — `(.*)`$/;

/** Roll every report up into per-rule counts and evidence samples. */
function collect(options) {
  const files = readdirSync(options.dir)
    .filter((name) => name.endsWith('.md') && name !== 'README.md' && name !== 'CALIBRATION.md');
  const rules = new Map();
  let packages = 0;
  for (const file of files) {
    let currentSeverity;
    let currentRule;
    let sawFinding = false;
    for (const line of readFileSync(join(options.dir, file), 'utf8').split('\n')) {
      const heading = HEADING.exec(line);
      if (heading !== null) {
        currentSeverity = heading[1];
        continue;
      }
      const finding = FINDING.exec(line);
      if (finding !== null) {
        sawFinding = true;
        currentRule = finding[1];
        if (!rules.has(currentRule)) rules.set(currentRule, { severity: currentSeverity, packages: new Set(), evidence: [] });
        rules.get(currentRule).packages.add(file);
        continue;
      }
      const evidence = EVIDENCE.exec(line);
      if (evidence === null || currentRule === undefined) continue;
      const entry = rules.get(currentRule);
      if (entry.evidence.length < options.evidence * 3) entry.evidence.push({ where: evidence[1], text: evidence[2] });
    }
    if (sawFinding) packages += 1;
  }
  return { rules, packages, files: files.length };
}

const options = parseArgs(process.argv.slice(2));
const { rules, packages, files } = collect(options);

const rows = [...rules.entries()]
  .filter(([, value]) => options.severity === 'ALL' || value.severity === options.severity)
  .sort((left, right) => right[1].packages.size - left[1].packages.size);

console.log(`reports: ${files}  packages with findings: ${packages}`);
console.log(`rules at ${options.severity} severity, by number of packages hit:\n`);
for (const [id, value] of rows) {
  const percent = Math.round((value.packages.size / files) * 100);
  console.log(`${String(value.packages.size).padStart(3)}× ${String(percent).padStart(3)}%  ${id}`);
}
console.log('');
for (const [id, value] of rows.slice(0, 12)) {
  console.log(`=== ${id}  (${value.packages.size} packages, ${value.severity}) ===`);
  const seen = new Set();
  for (const item of value.evidence) {
    const key = item.text.slice(0, 60);
    if (seen.has(key)) continue;
    seen.add(key);
    console.log(`   ${item.where}  ::  ${item.text.slice(0, 150)}`);
    if (seen.size >= options.evidence) break;
  }
  console.log('');
}
